server:
  port: 3001
  servlet:
    context-path: /api/private/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vsdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
